import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored and generated assets, not source: the minified pdf.js worker
    // and the subsetted résumé fonts.
    "public/**",
    // Verification artefacts, regenerated by `npm run verify:templates`.
    ".verify/**",
  ]),

  /**
   * The résumé engine may not know that any particular template exists.
   *
   * This is the rule that keeps "add a template without touching the engine"
   * honest: the moment `core/` imports a template, the abstraction has leaked,
   * and the next template will need engine changes too.
   */
  {
    files: ["src/resume/core/**/*.{ts,tsx}"],
    ignores: ["src/resume/core/**/*.test.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/templates/*", "../templates/*", "@/resume/templates/*"],
              message:
                "core/ must not import a specific template. Templates are data; the engine interprets them. See docs/resume-builder/ADDING-A-TEMPLATE.md.",
            },
          ],
        },
      ],
    },
  },
]);

export default eslintConfig;
