/**
 * LaTeX output.
 *
 * The emitter knows nothing about any particular template: each one ships its
 * own preamble and a set of `{{slot}}` macro strings, and this module fills
 * them in. That is what keeps "add a template without touching the engine" true
 * for the TEX export as well as the PDF.
 *
 * Placeholders:
 *   {{organization}} … any entry slot, plus {{dateRange}}
 *   {{name}} {{contact}} {{title}} {{text}}
 *   {{bullets}}   expands via `profile.bullet`, one line per bullet
 *   {{entries}}   inside `section`
 *   {{header}} {{body}} {{side}}  inside `document`
 */

import {
  formatDateRange,
  hrefForLink,
  isSectionEmpty,
  sectionColumn,
  type ResumeDoc,
  type Section,
} from "../model";
import type { LatexProfile, TemplateDefinition } from "../schema";

/** Order matters: the backslash must be replaced first. */
const ESCAPES: [RegExp, string][] = [
  [/\\/g, "\\textbackslash{}"],
  [/([&%$#_{}])/g, "\\$1"],
  [/~/g, "\\textasciitilde{}"],
  [/\^/g, "\\textasciicircum{}"],
  [/–/g, "--"],
  [/—/g, "---"],
  [/“|”/g, '"'],
  [/‘|’/g, "'"],
  [/•/g, "\\textbullet{}"],
  [/…/g, "\\ldots{}"],
];

export function escapeLatex(input: string, extra: Record<string, string> = {}): string {
  let out = input;
  for (const [pattern, replacement] of ESCAPES) out = out.replace(pattern, replacement);
  for (const [from, to] of Object.entries(extra)) out = out.split(from).join(to);
  // Pasted URLs and other unhyphenated tokens overfull the measure unless TeX
  // is allowed to break them. Commands and escaped specials contain `\` or `{}`
  // and are left alone.
  out = out.replace(/[^\s\\{}]{32,}/g, (token) => {
    const parts: string[] = [];
    for (let i = 0; i < token.length; i += 12) parts.push(token.slice(i, i + 12));
    return parts.join("\\allowbreak{}");
  });
  return out;
}

/** `\href` first argument: keep the URL intact, escape only TeX specials. */
function escapeHref(url: string): string {
  return url.replace(/\\/g, "\\\\").replace(/([#%{}&])/g, "\\$1");
}

/**
 * Fills `{{slot}}` placeholders. Missing slots collapse to an empty string, and
 * a line left with nothing but whitespace is dropped — so an entry without a
 * location does not leave a stray blank line in the .tex.
 */
function fill(templateString: string, values: Record<string, string>): string {
  const filled = templateString.replace(/\{\{\s*(\w+)\s*\}\}/g, (_, key: string) =>
    values[key] ?? "",
  );
  return filled
    .split("\n")
    .filter((line, i, all) => line.trim() !== "" || (i > 0 && all[i - 1].trim() !== ""))
    .join("\n");
}

function bulletsFor(
  profile: LatexProfile,
  bullets: string[],
  extra: Record<string, string>,
): string {
  const items = bullets.filter((b) => b.trim());
  if (!items.length) return "";
  const body = items
    .map((item) => fill(profile.bullet ?? "\\item {{item}}", { item: escapeLatex(item, extra) }))
    .join("\n");
  return [profile.bulletsOpen, body, profile.bulletsClose].filter(Boolean).join("\n");
}

export function renderLatex(doc: ResumeDoc, template: TemplateDefinition): string {
  const profile = template.emit.latex;
  const extra = profile.extraEscapes ?? {};
  const esc = (s: string | undefined) => escapeLatex(s ?? "", extra);

  const contact = doc.personal.links
    .filter((l) => l.label.trim())
    .map((l) => {
      const href = hrefForLink(l);
      const label = esc(l.label);
      return href && l.kind !== "location" && l.kind !== "other"
        ? `\\href{${escapeHref(href)}}{${label}}`
        : label;
    })
    .join(" $\\bullet$ ");

  const header = fill(profile.header, {
    name: esc(doc.personal.name),
    headline: esc(doc.personal.headline),
    contact,
  });

  const rendered = doc.sections
    .filter((s) => !isSectionEmpty(s))
    .map((section) => ({
      column: sectionColumn(section, template.sections.sideKinds),
      tex: renderSection(section, doc, template, profile, extra),
    }))
    .filter((s) => s.tex);

  const main = rendered
    .filter((s) => s.column === "main")
    .map((s) => s.tex)
    .join("\n\n");
  const side = rendered
    .filter((s) => s.column === "side")
    .map((s) => s.tex)
    .join("\n\n");

  const hasSideSlot = /\{\{\s*side\s*\}\}/.test(profile.document);
  const body = hasSideSlot ? main : [main, side].filter(Boolean).join("\n\n");

  const document = fill(profile.document, { header, body, side });

  return [
    "% Generated by the IEM RVCE Resume Builder.",
    "% Compile with " + (template.meta.engine === "xelatex" ? "xelatex" : "pdflatex") + ".",
    "% Everything below is plain LaTeX — edit it freely.",
    "",
    profile.documentClass,
    profile.preamble,
    "",
    "% Let long student tokens (URLs, German compounds) break rather than overfull.",
    "\\emergencystretch=3em",
    "",
    document,
    "",
  ].join("\n");
}

function renderSection(
  section: Section,
  doc: ResumeDoc,
  template: TemplateDefinition,
  profile: LatexProfile,
  extra: Record<string, string>,
): string {
  const esc = (s: string | undefined) => escapeLatex(s ?? "", extra);
  const sectionTpl =
    profile.sectionFor?.[section.kind] ?? profile.sectionFor?.[section.layout] ?? profile.section;
  const pick =
    profile.entry[section.kind] ?? profile.entry[section.layout] ?? profile.entry.default ?? "";

  let entries: string;

  if (section.layout === "paragraph") {
    if (!section.text?.trim()) return "";
    entries = fill(profile.entry.paragraph ?? pick, { text: esc(section.text) });
  } else {
    entries = section.entries
      .filter(
        (e) =>
          e.organization?.trim() ||
          e.position?.trim() ||
          e.summary?.trim() ||
          e.bullets.some((b) => b.trim()),
      )
      .map((entry) =>
        fill(pick, {
          organization: esc(entry.organization),
          position: esc(entry.position),
          location: esc(entry.location),
          summary: esc(entry.summary),
          detail: esc(entry.detail),
          url: entry.url ?? "",
          dateRange: esc(formatDateRange(entry, template.conventions.dateDash)),
          tags: esc(entry.tags.filter(Boolean).join(", ")),
          rating: entry.rating == null ? "" : String(entry.rating),
          bullets: bulletsFor(profile, entry.bullets, extra),
        }),
      )
      .join("\n");
  }

  if (!entries.trim()) return "";
  return fill(sectionTpl, { title: esc(section.title), entries });
}

export function texBlob(source: string): Blob {
  return new Blob([source], { type: "application/x-tex" });
}
